apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: pythonApp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: giaple/gotest:latest
        ports:
        - containerPort: 8081
---          
#namespace
apiVersion: v1
kind: Namespace
metadata:
  name: giaplv-app-python 
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: go-demo
#spec:
#  containers:
#  - name: go-demo
#    image: debian
#    terminationMessagePath: "/tmp/my-log"
